- README.md
- load_testing/locustfile.py
- Don't use full urls with locust so that the `--host` setting works.
- Remove test against non-IDP endpoint, we'll do that with different locustfiles
- Add some simple error handling around often mis-configured IDP options
> Allow changing hosts from command-line

- load_testing/common_flows/flow_helper.py
- load_testing/common_flows/flow_ial2_proofing.py
- load_testing/common_flows/flow_sign_in.py
- load_testing/common_flows/flow_sign_up.py
When a locust runs into an error, immediately restart it.
This prevents the broken thread from continuing until the end of the flow, triggering more errors along the way.
> Cleaner errors from Locust

- README.md
- load_testing/common_flows/flow_helper.py
- load_testing/common_flows/flow_ial2_proofing.py
- load_testing/common_flows/flow_sign_in.py
- load_testing/common_flows/flow_sign_up.py
- load_testing/common_flows/flow_sp_sign_in.py
- load_testing/ial2_sign_in.locustfile.py
- load_testing/ial2_sign_up.locustfile.py
- load_testing/sign_in.locustfile.py
- load_testing/sign_up_sign_in.locustfile.py
- load_testing/sp_sign_in.locustfile.py
This adds a flow for SP logins.  
It requires that a Service Provider host is:
- running
- configured to work with the IdP host
- passed in via `SP_HOST` env variable
Right now this probably only works with <https://github.com/18F/identity-oidc-sinatra>.
If that's not what we run in real life, we can generalize things a bit more later.
Closes https://github.com/18F/identity-devops/issues/2249
> Service provider (SP) Sign In flow

- load_testing/common_flows/flow_helper.py
- load_testing/common_flows/flow_ial2_proofing.py
- load_testing/ial2_sign_in.locustfile.py
- load_testing/ial2_sign_up.locustfile.py
- tests/test_flow_helpers.py
Prevents file descriptor starvation due to many concurrent Locust
processes holding open file descriptors while POSTing data.
> Preload driver's license image data

- load_testing/common_flows/flow_sign_in.py
- load_testing/sign_in_remember_me.locustfile.py
For https://github.com/18F/identity-devops/issues/2416
Locally this seems to work, it only hits the `/sms` path once compared to the sign_in flow which hits it every time
> Add option for sign_in flow to remember device, skip OTP on future runs

- load_testing/common_flows/flow_helper.py
- load_testing/common_flows/flow_sign_in.py
- load_testing/sign_in_failure.locustfile.py
- load_testing/sign_in_remember_me.locustfile.py
- tests/test_flow_helpers.py
* sign_in helper records users as they visit, then starts replaying after
threhold is met, attempting to hit remembered sign in target.
* sign_in helper uses per-user cookie cache to restore
"user_opted_remember_device_preference" and "remember_device"
cookies for a given user.
Able to push over 90% remembered device mix.
> Add persistent cookie handling for remembered device sign in

- README.md
- load_testing/common_flows/flow_helper.py
- load_testing/common_flows/flow_sp_sign_in.py
This makes the changes needed to use the form based login button in the [sample SP app](https://github.com/18F/identity-oidc-sinatra). I also made some minor readme updates by adding a note about scrypt cost in the IdP config and removed the ` SCRYPT_COST='800$8$1$'`, which we don't want in the load test and did not seem to function correctly anyhow: https://gsa-tts.slack.com/archives/C010L0SE4E8/p1600987482033000.
I also used the default pylint settings to update the formatting of the modified files in this change.
These changes were made in support of https://github.com/18F/identity-devops/issues/2192
One can test these changes by running locally against the `pt` env:
```
NUM_USERS=10000 SP_HOST=https://sp-oidc-sinatra.pt.identitysandbox.gov/ locust --locustfile …
```
> SP sign in method updates

- load_testing/common_flows/flow_ial2_proofing.py
- load_testing/ial2_sign_in.locustfile.py
This makes the changes needed to be on par with the IAL2 flows that exist in the [current version of the IdP](https://github.com/18F/identity-idp/commit/ba7164937e8eb851291014e377328039c71b0045). 
```
locust --host https://idp.pt.identitysandbox.gov --locustfile load_testing/ial2_sign_up.locustfile.py --users 100 --hatch-rate 1 --headless --csv ial2_sign_up
```
Note there are still errors with `GET                  /sign_up/enter_email` which I'll fix in a subsequent PR since it's not related to #27.
```
Name                                                          # reqs      # fails     Avg     Min     Max  |  Median   req/s failures/s
--------------------------------------------------------------------------------------------------------------------------------------------
GET /account …
```
> Update IAL2 requests to match current IdP + pylint

- requirements.txt
Simple fix for https://gsa-tts.slack.com/archives/C010L0SE4E8/p1620861178002700
Tested on OSX https://gsa-tts.slack.com/archives/C010L0SE4E8/p1620864092005300 and on the jumphost: https://gsa-tts.slack.com/archives/C010L0SE4E8/p1620864574005900
> Update faker to latest for python 3.9.4+ compatibility

- load_testing/common_flows/flow_helper.py
- load_testing/common_flows/flow_sign_in.py
- load_testing/common_flows/flow_sp_ial2_sign_in.py
- load_testing/common_flows/flow_sp_ial2_sign_up.py
- load_testing/common_flows/flow_sp_sign_in.py
- load_testing/common_flows/flow_sp_sign_up.py
- load_testing/prod_simulator.locustfile.py
- load_testing/sp_sign_in.locustfile.py
Open issues:
- This was fixed by clearing the cookies in the sign up flow. I believe the user cookies from the end of the sign in flow were used for the sign up flow causing the error.
> Add SP Sign In and Sign Up methods to the prod_simulator fllow

- load_testing/sp_sign_up.locustfile.py
Fixes 
```
[2021-07-02 22:22:06,753] jumphost-i-022ff37d06ccb80e1.pt.identitysandbox.gov/ERROR/locust.user.task: module 'common_flows.flow_sp_sign_up' has no attribute 'do_sp_sign_up'
Traceback (most recent call last):
File "/usr/local/lib/python3.6/dist-packages/locust/user/task.py", line 290, in run
lf.execute_next_task()
File "/usr/local/lib/python3.6/dist-packages/locust/user/task.py", line 315, in execute_next_task
lf.execute_task(self._task_queue.pop(0))
File "/usr/local/lib/python3.6/dist-packages/locust/user/task.py", line 327, in execute_task
sk(self)
Fi "/etc/login.gov/repos/identity-loadtest/load_testing/sp_sign_up.locustfile.py", line 9, in sp_sign_up_load_test
flow_sp_sign_up.do_sp_sign_up(self)
AttributeError: module 'common_flows.flow_sp_sign_up' has no attribute …
```
> Wrong function referenced in sp_sign_up flow

- load_testing/common_flows/flow_sp_sign_in.py
This fixes a regression from the last PR. It was failing in the sign in flow when `remember_device` was set but there were no logged in users available.
```
SP_HOST=https://sp-oidc-sinatra.pt.identitysandbox.gov NUM_USERS=10000 /usr/local/bin/locust --host https://idp.pt.identitysandbox.gov --locustfile load_testing/prod_simulator.locustfile.py --users 100 --spawn-rate 10 --run-time 2m --logfile /tmp/locust.log --headless
Name                                                          # reqs      # fails  |     Avg     Min     Max  Median  |   req/s failures/s
--------------------------------------------------------------------------------------------------------------------------------------------
GET /                                                            258     0(0.00%)  |      69 …
```
> Only set expected path to SP url if remembered is set

- load_testing/common_flows/flow_helper.py
One more expected fail text to better understand why a request fails.
> Add 503 response to expected fail texts

- load_testing/sp_ial2_sign_in.locustfile.py
- load_testing/sp_ial2_sign_up.locustfile.py
This creates dedicated flows for SP based IAL2 sign in/up which can be used with the `id-locust` helper script. Currently the only way to do this is via the prod_simulator flow.
sp_ial2_sign_up
```
+ locust --host https://idp.pt.identitysandbox.gov --locustfile /etc/login.gov/repos/identity-loadtest/load_testing/sp_ial2_sign_up.locustfile.py --users 10 --spawn-rate 1 --headless --csv /var/log/loadtest/20210727194640-sp_ial2_sign_up --run-time 15m
/usr/lib/python3/dist-packages/requests/__init__.py:80: RequestsDependencyWarning: urllib3 (1.26.6) or chardet (3.0.4) doesn't match a supported version!
RequestsDependencyWarning)
[2021-07-27 19:46:41,307] jumphost-i-030fc47cf42e30503.pt.identitysandbox.gov/INFO/locust.main: Run time limit set to 900 seconds
[2021-07-27 19:46:41,307] …
```
> Dedicated flows for SP based IAL2 flows

- load_testing/common_flows/flow_helper.py
- load_testing/common_flows/flow_sp_ial2_sign_in_async.py
- load_testing/common_flows/flow_sp_ial2_sign_up_async.py
- load_testing/sp_ial2_sign_in_async.locustfile.py
- load_testing/sp_ial2_sign_up_async.locustfile.py
There are subtle differences in the IAL2 flows when the async workers are enabled. This adds two new IAL2 flows so we can load test the async workers. It may look like a big change but most of it is CPd from https://github.com/18F/identity-loadtest/blob/main/load_testing/common_flows/flow_sp_ial2_sign_up.py and https://github.com/18F/identity-loadtest/blob/main/load_testing/common_flows/flow_sp_ial2_sign_in.py.  There's plenty of opportunity to DRY up the code, @vchugh has already started on that: https://github.com/18F/identity-loadtest/pull/45. 
You can run this locally or from the jumphost
```
export SP_HOST=https://sp-oidc-sinatra.pt.identitysandbox.gov
export NUM_USERS=2000000 
cd identity-loadtest
locust \
--host https://idp.pt.identitysandbox.gov \
--locustfile …
```
> Add SP IAL2 flows for async workers

- load_testing/common_flows/flow_ial2_proofing.py
- load_testing/common_flows/flow_sp_ial2_sign_in.py
- load_testing/common_flows/flow_sp_ial2_sign_in_async.py
- load_testing/common_flows/flow_sp_ial2_sign_up.py
- load_testing/common_flows/flow_sp_ial2_sign_up_async.py
Since we'll be changing what SSNs are valid in the lower environments in https://github.com/18F/identity-idp/pull/5576
Not sure if we still want randomness here, but I changed to a static placeholder for now
> update to use valid SSNs

- load_testing/common_flows/flow_ial2_proofing.py
- load_testing/common_flows/flow_sign_up.py
- load_testing/common_flows/flow_sp_ial2_sign_in.py
- load_testing/common_flows/flow_sp_ial2_sign_in_async.py
- load_testing/common_flows/flow_sp_ial2_sign_up.py
- load_testing/common_flows/flow_sp_ial2_sign_up_async.py
- load_testing/common_flows/flow_sp_sign_up.py
The IDP expects to compare to a value of `"1"` instead of `"true"` now
> send 1 instead of true for checkboxes

- requirements.txt
Apparently version `6.3.2` is not available in the python env on our instances. 
```
* execute[install_locust] action run[2022-05-24T18:25:40+00:00] INFO: Processing execute[install_locust] action run (identity-jumphost::default line 114)
[execute] ERROR: Could not find a version that satisfies the requirement coverage==6.3.2 (from versions: 3.0b3, 3.0, 3.0.1, 3.1b1, 3.1, 3.2b1, 3.2b2, 3.2b3, 3.2b4, 3.2, 3.3, 3.3.1, 3.4b1, 3.4b2, 3.4, 3.5b1, 3.5, 3.5.1b1, 3.5.1, 3.5.2b1, 3.5.2, 3.5.3, 3.6b1, 3.6b2, 3.6b3, 3.6, 3.7, 3.7.1, 4.0a1, 4.0a2, 4.0a3, 4.0a4, 4.0a5, 4.0a6, 4.0b1, 4.0b2, 4.0b3, 4.0, 4.0.1, 4.0.2, 4.0.3, 4.1b1, 4.1b2, 4.1b3, 4.1, 4.2b1, 4.2, 4.3, 4.3.1, 4.3.2, 4.3.3, 4.3.4, 4.4b1, 4.4, 4.4.1, 4.4.2, 4.5, 4.5.1, 4.5.2, 4.5.3, 4.5.4, 5.0a1, 5.0a2, 5.0a3, 5.0a4, 5.0a5, 5.0a6, 5.0a7, …
```
> Reverts version of coverage libary

- requirements.txt
Our loadtest nodes still run Python 3.6 which is not compatible with locust 2.9
> Revert to locust 2.8.6

- load_testing/common_flows/flow_sp_ial2_sign_up.py
- load_testing/common_flows/flow_sp_sign_up.py
This change keeps this loadtest code in sync with the IdP https://github.com/18F/identity-idp/commit/cdea08fd55ff2f8a1e92a60009dad5b57a491e63
> Keep the sign_up flows in sync with the IdP

- tests/test_flow_helpers.py
- tests/test_helper.py
This should resolve the problem with tests when run outside of the root of the repo.
> Make tests not care where you call pytest from

- load_testing/lib/flow_helper.py
- load_testing/lib/flow_sp_sign_in.py
- load_testing/lib/flow_sp_sign_up.py
- load_testing/prod_simulator.locustfile.py
This adds a step to confirm the logout on the IdP as described in https://github.com/18F/identity-loadtest/issues/63.
I'm currently running into an error where it fails on the POST due to an unexpected redirect: 
```
ulimit -n 10240                             
export NUM_USERS=2000000
export SP_HOST=https://oidc-sinatra.loadtest.identitysandbox.gov/
export DEBUG=true
locust \
--host https://idp.pt.identitysandbox.gov \
--locustfile load_testing/sp_sign_in.locustfile.py \
--headless \
--logfile /tmp/locust.log \
--spawn-rate 6 \
--run-time 1m \
--users 1
```
```
Error report
------------------|---------------------------------------------------------------------------------------------------------------------------------------------
2                  POST /openid_connect/logout: …
```
> Updates flow with new IdP logout confirmation step

- load_testing/lib/flow_helper.py
- load_testing/lib/flow_sp_ial2_sign_up.py
- load_testing/lib/flow_sp_sign_in.py
- load_testing/lib/flow_sp_sign_up.py
This updates the identity verification flows, but excludes the "async" and ial2_sign_up since we are focused on prod-like environments.
Matches the behavior of production
> Update identity verification flows

- load_testing/lib/flow_helper.py
This PR fixes EC2-backed `locust-*` instances which are failing with the following message:
`unsupported operand type(s) for |: 'dict' and 'dict',"`
> Update flow_helper.py to work on EC2 and EKS

- locust.yaml
It's running 2.13.1, which I think is newer than what we have out there now.
> new version of locust chart dropped

- load_testing/lib/flow_ial2_proofing.py
- load_testing/lib/flow_sp_ial2_sign_in.py
- load_testing/lib/flow_sp_ial2_sign_in_async.py
- load_testing/lib/flow_sp_ial2_sign_up.py
- load_testing/lib/flow_sp_ial2_sign_up_async.py
- load_testing/lib/flow_sp_sign_up.py
Last change needed to get us back on track.
```
locust \                             
--host https://idp.pt.identitysandbox.gov \
--locustfile load_testing/prod_simulator.locustfile.py \
--headless \
--logfile /tmp/locust.log \
--spawn-rate 6 \
--users 32
```
```
--------|----------------------------------------------------------------------------|-------|-------------|-------|-------|-------|-------|--------|-----------
POST     /                                                                                 52     0(0.00%) |    751     522    1322    700 |    3.20        0.00
POST     /auth_method_confirmation/skip …
```
> update doc auth urls

- terraform/loadtest_cluster.tf
This matches the version which the cluster was manually updated to via the web console.
> update cluster version

- locust.yaml
This updates the image in ECR with locust 2.28.0. I did so using the following commands:
```
brew install --cask docker
docker pull locustio/locust:2.28.0
aws-vault exec sandbox-admin -- aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin <aws_account>.dkr.ecr.us-west-2.amazonaws.com
docker tag locustio/locust:2.28.0 <aws_account>..dkr.ecr.us-west-2.amazonaws.com/locustio/locust:2.28.0
docker push <aws_account>..dkr.ecr.us-west-2.amazonaws.com/locustio/locust:2.28.0
```
This also updates the dependencies installed via pip.
> Update EKS locust bits
