18F/identity-loadtest

- README.md
- load_testing/locust_helpers.py
- load_testing/sign_in.locustfile.py
- load_testing/sign_up.locustfile.py
- Adds a simple sign in/out flow
- Splits the tests into two files for now
- README formatting
> Sign in / out flow

- README.md
- load_testing/common_flows/flow_helper.py
- load_testing/common_flows/flow_ial2_proofing.py
- load_testing/common_flows/flow_sign_in.py
- load_testing/common_flows/flow_sign_up.py
- load_testing/common_flows/helper_phony.py
- load_testing/ial2_sign_in.locustfile.py
- load_testing/ial2_sign_up.locustfile.py
- load_testing/sign_in.locustfile.py
- load_testing/sign_up.locustfile.py
- Add Sign-Up + IAL2 Flow
- Refactor flows to be reusable
- Also used a Python formatter, so sorry about some diff noise
Closes https://github.com/18F/identity-devops/issues/2248
> IAL2  sign up flow

- load_testing/common_flows/flow_sign_up.py
- Go back to old way of making PATCH request
> Fix phone_setup tests for 'pt' env

- .gitignore
- README.md
- load_testing/common_flows/flow_ial2_proofing.py
- load_testing/common_flows/flow_sign_up.py
- load_testing/sign_up.locustfile.py
- load_testing/sign_up_sign_in.locustfile.py
Adds a weighted IAL1 Sign-Up + Sign-In flow
> Weighted Sign-Up + Sign-In flow

- load_testing/common_flows/flow_helper.py
This adds the Response body to unexpected redirect errors when `DEBUG=true`
It also should raise an error for HTTP status before checking redirects.
> DEBUG=true for more error output

- load_testing/common_flows/flow_helper.py
This will display things like posted email address for login, phone number used, etc.
> Add DEBUG information for requests

- .circleci/config.yml
- .coveragerc
- .gitignore
- README.md
- load_testing/common_flows/flow_helper.py
- load_testing/common_flows/flow_ial2_proofing.py
- load_testing/requirements.txt
- requirements.txt
- tests/fixtures/doc_auth_verify.html
- tests/fixtures/sp_with_session.html
- tests/fixtures/sp_without_session.html
- tests/fixtures/two_factor_sms.html
- tests/fixtures/verify_email.html
- tests/test_flow_helpers.py
- tests/test_helper.py
- Uses Pytest
- Includes optional coverage
- Includes some static html files to test against
- Includes CirlceCI config
> Add some tests

- load_testing/common_flows/flow_sign_in.py
- load_testing/sign_in_failure.locustfile.py
Adds alternate sign in tests and a `sign_in_failure` Locust file
for running all three scenarios.
TODO - Can be integrated into a "prod simulator" super Locust file.
> Add missing user, bad password, and bad OTP sign in tests

- README.md
- load_testing/prod_simulator.locustfile.py
- load_testing/sign_in_remember_me.locustfile.py
* Uses ratios measured on 5/18/2020
* Allows tuning via environment variable
* Validated with test run showing simulation +/- 1% of production measurement
> Add simulator load test

- load_testing/ial2_sign_in.locustfile.py
- load_testing/ial2_sign_up.locustfile.py
- load_testing/prod_simulator.locustfile.py
- load_testing/sign_in.locustfile.py
- load_testing/sign_in_failure.locustfile.py
- load_testing/sign_in_remember_me.locustfile.py
- load_testing/sign_up.locustfile.py
- load_testing/sign_up_sign_in.locustfile.py
- load_testing/sp_sign_in.locustfile.py
- requirements.txt
Upgrading to take advantage of new features and to stop having to translate command line options when reading new documents.  
Pairs with https://github.com/18F/identity-devops/pull/2534
> Upgrade from Locust 0.14.5 to Locust 1.0.3

- load_testing/common_flows/flow_sp_sign_up.py
- load_testing/sp_sign_up.locustfile.py
This adds a sign up only flow with our example service provider.
```
SP_HOST=https://sp-oidc-sinatra.pt.identitysandbox.gov locust --locustfile load_testing/sp_sign_up.locustfile.py --host https://idp.pt.identitysandbox.gov  --users 100 --run-time 30m --headless
...
...
[2021-03-03 16:07:56,440] j12/INFO/locust.main: Time limit reached. Stopping Locust.
[2021-03-03 16:07:56,550] j12/INFO/locust.main: Running teardowns...
[2021-03-03 16:07:56,550] j12/INFO/locust.main: Shutting down (exit code 0), bye.
[2021-03-03 16:07:56,550] j12/INFO/locust.main: Cleaning up runner...
Name                                                          # reqs      # fails     Avg     Min     Max  |  Median   req/s failures/s
--------------------------------------------------------------------------------------- …
```
> Add SP based sign up flow

- README.md
Fixes https://docs.locust.io/en/stable/changelog.html#id12
> Update deprecated config key in readme

- load_testing/common_flows/flow_ial2_proofing.py
- load_testing/prod_simulator.locustfile.py
This makes a few updates to the prod simulator flow, namely:
- Update the ratios to match current data from CloudWatch
- Only show print statements with DEBUG flag set
- Add new step to IdV flow `verify/doc_auth/agreement`
> Prod simulator flow updates

- load_testing/common_flows/flow_helper.py
- load_testing/common_flows/flow_ial2_proofing.py
- load_testing/common_flows/flow_sign_in.py
- load_testing/common_flows/flow_sign_up.py
- load_testing/common_flows/flow_sp_ial2_sign_in.py
- load_testing/common_flows/flow_sp_ial2_sign_up.py
- load_testing/common_flows/flow_sp_sign_in.py
- load_testing/common_flows/flow_sp_sign_up.py
- load_testing/ial2_sign_in.locustfile.py
- load_testing/ial2_sign_up.locustfile.py
- load_testing/prod_simulator.locustfile.py
- load_testing/sign_in.locustfile.py
- load_testing/sign_in_failure.locustfile.py
- load_testing/sign_in_remember_me.locustfile.py
- load_testing/sign_up.locustfile.py
- load_testing/sign_up_sign_in.locustfile.py
- tests/test_flow_helpers.py
Update sign in methods to not reuse users by providing the `random_cred` function an array of already used test users:
While working on this I also noticed that a number of our error checking statements were not failing the requests as expected so I refactored the `do_request` method to handle the errors by checking for `expected_text` within its `with statement` and also included some additional functions to better track errors (`check_fail_text`). This required adding another argument to the `do_request` functions used throughout the app. At some point we may want to have `do_requets` take a dictionary of options to DRY up the code.
This also migrates more print statements to the native logging facility which writes to a file. Furthermore, I have moved log events to their respective log …
> Prevent user reuse in sign_in flows

- load_testing/common_flows/flow_sp_ial2_sign_up_async.py
A route changed in the IdP code and needs updating here.
> Update flow for https://github.com/18F/identity-idp/pull/5785

- load_testing/common_flows/flow_sp_sign_up.py
This fixes a line that hardcoded the expected SP host URL and prevented the signup test from successfully running in environments other than `pt`.
<details><summary>example sp signup run</summary>
```
ulimit -n 10240
export SP_HOST=https://sp-oidc-sinatra.pt2.identitysandbox.gov
locust \
--host https://idp.pt2.identitysandbox.gov \
--locustfile load_testing/sp_sign_up.locustfile.py \
--headless \
--logfile /tmp/locust.log \
--spawn-rate 6 \
--run-time 1m \
--users 120
```
</details>
<details><summary>without fix</summary>
```
--------|----------------------------------------------------------------------------|-------|------------- …
```
> Don't hardcode SP host

- .gitignore
- kustomization.yaml
- locust.yaml
- terraform/.terraform.lock.hcl
- terraform/README.md
- terraform/deploy.sh
- terraform/loadtest_cluster.tf
- terraform/main.tf
- terraform/variables.tf
Creates EKS cluster with argocd in it, and has a quick first stab at getting locust going in it.
> Create loadtest cluster stuff

- load_testing/lib/flow_sign_up.py
- load_testing/lib/flow_sp_ial2_sign_up.py
- load_testing/lib/flow_sp_ial2_sign_up_async.py
- load_testing/lib/flow_sp_sign_up.py
- tests/test_flow_helpers.py
Updates sign up flows to match the IDP for both IAL1/IAL2
Not sure why the fixture test is failing though
> Update sign up flows

- load_testing/lib/flow_sp_ial2_sign_in.py
This fixes the error in the IAL2 sign in flow so the image upload can complete. That said, we need to ensure that users are not already proofed when using this flow.
With fix
```
PUT      /verify/doc_auth/agreement                                                        14     0(0.00%) |    309     188     516    300 |    0.46        0.00
PUT      /verify/doc_auth/document_capture                                                  2     0(0.00%) |    313     305     322    310 |    0.07        0.00
PUT      /verify/doc_auth/ssn                                                               2     0(0.00%) |    243     224     262    224 |    0.07        0.00
PUT      /verify/doc_auth/upload?type=desktop                                              14     0(0.00%) |    297     199     586 …
```
> Fix to bring the IAL2 sign in flow up to speed

- load_testing/lib/flow_sp_ial2_sign_in.py
https://gsa-tts.slack.com/archives/C010L0SE4E8/p1674600894130909?thread_ts=1674597450.371399&cid=C010L0SE4E8
```
--------|----------------------------------------------------------------------------|-------|-------------|-------|-------|-------|-------|--------|-----------
GET      /                                                                                  6     0(0.00%) |     54      38      71     44 |    0.09        0.00
POST     /                                                                                152     0(0.00%) |    605     262     909    600 |    2.33        0.00
POST     /api/verify/images …
```
> Update test flow to match current IdP

- load_testing/lib/flow_sp_ial2_sign_up.py
fixes script after https://github.com/18F/identity-idp/pull/7747
> fix identity proofing after removing some of FSM

- scripts/verify_users.rb
Script for adding users to an environment through the Rails console.
> Verify and add users for load testing

- requirements.txt
I could not get this to build on an ARM based mac without updating. This works locally on my mac with python 3.11. 
```
--------|----------------------------------------------------------------------------|-------|-------------|-------|-------|-------|-------|--------|-----------
GET      /                                                                                  2     0(0.00%) |     77      73      81     73 |    0.01        0.00
POST     /                                                                                 39     0(0.00%) |    989     287    2331    880 |    0.22        0.00
POST     /api/verify/images …
```
> Update locust and dependencies

- load_testing/lib/flow_helper.py
- load_testing/lib/flow_sp_ial2_sign_in.py
- load_testing/lib/flow_sp_ial2_sign_in_async.py
- load_testing/lib/flow_sp_ial2_sign_up_async.py
- load_testing/lib/flow_sp_sign_in.py
- tests/fixtures/verify_email.html
It does what the title says. This fixes the errors I was getting when running the prod simulator.
> Removes the request_id param which is no longer needed

- .circleci/config.yml
- requirements.txt
No code changes are needed, just package updates.
> Updates locust and dependencies

- load_testing/all_flows.locustfile.py
- load_testing/ial2_sign_in.locustfile.py
- load_testing/ial2_sign_up.locustfile.py
- load_testing/lib/flow_helper.py
- load_testing/lib/flow_ial2_proofing.py
- load_testing/lib/flow_sign_in.py
- load_testing/lib/flow_sign_up.py
- load_testing/lib/flow_sp_ial2_sign_in.py
- load_testing/lib/flow_sp_ial2_sign_in_async.py
- load_testing/lib/flow_sp_ial2_sign_up.py
- load_testing/lib/flow_sp_ial2_sign_up_async.py
- load_testing/lib/flow_sp_sign_in.py
- load_testing/lib/flow_sp_sign_up.py
- load_testing/prod_simulator.locustfile.py
- load_testing/sign_in_remember_me.locustfile.py
- load_testing/sign_up_sign_in.locustfile.py
- load_testing/sp_ial2_sign_in_async.locustfile.py
- load_testing/sp_ial2_sign_up_async.locustfile.py
- requirements.txt
- tests/test_flow_helpers.py
- tests/test_helper.py
The title says it all. This fixes all code drift errors and resuscitates the IdP-only tests. I also added a new `all_flows` test to ensure all tests run without error. You can test out the `all_flows` test for 5m with the following commands:
```
export SP_HOST=https://oidc-sinatra.loadtest.identitysandbox.gov                              
export NUM_USERS=1000000
locust --headless  --host https://idp.pt.identitysandbox.gov --locustfile load_testing/all_flows.locustfile.py --logfile /tmp/locust.log -u 8 -t 5m
```
Example output:
```
--------|----------------------------------------------------------------------------|-------|------- …
```
> Fixes for IdP code drift, new all_flows test, and fixes for other bugs discovered along the way

- load_testing/lib/flow_ial2_proofing.py
- load_testing/lib/flow_sign_in.py
- load_testing/lib/flow_sign_up.py
- load_testing/lib/flow_sp_ial2_sign_in.py
- load_testing/lib/flow_sp_ial2_sign_in_async.py
- load_testing/lib/flow_sp_ial2_sign_up.py
- load_testing/lib/flow_sp_ial2_sign_up_async.py
Fixes https://github.com/18F/identity-loadtest/issues/85
> Migrate print statements to the native logging lib

- .github/pull_request_template.md
Added github PR Template to prevent creation of PR's
> Add default github pr template
